#ifndef _MESSAGE_H_20040427
#define _MESSAGE_H_20040427


#define WM_DATAARRIVE		(WM_USER+1)
#define WM_STOCKCHANGE		(WM_USER+2)
#define WM_TRADEDLGINFO		(WM_USER+3)
#define WM_ASKSTOCKINFO		(WM_USER+4)
#define WM_ASKSTOCKNAME		(WM_USER+5)
#define WM_TRADELOGININFO	(WM_USER+6)
#define WM_TASKMANAGE		(WM_USER+7)
#define WM_REQUESTDATA		(WM_USER+8)
#define WM_REDRAWWND		(WM_USER+9)
#define WM_LOGINCHANGEPWD   (WM_USER+10)
#define WM_KEYGHOSTMSG      (WM_USER+11)
#endif
